name: Validate Module

on: [pull_request, push]

jobs:
  validate:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Prerequisites
      shell: pwsh
      run: .\build\vsts-prerequisites.ps1
    - name: Validate
      run: .\build\vsts-validate.ps1
      shell: pwsh